// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {
    '404': { id: '404', path: '*', parentId: 'DocLayout' },
    'dumi-context-layout': { id: 'dumi-context-layout', path: '/', isLayout: true },
    DocLayout: { id: 'DocLayout', path: '/', parentId: 'dumi-context-layout', isLayout: true },
    'docs/demos/disabledDate': {
      path: 'demos/disabled-date',
      id: 'docs/demos/disabledDate',
      parentId: 'DocLayout',
    },
    'docs/demos/uncontrolled': {
      path: 'demos/uncontrolled',
      id: 'docs/demos/uncontrolled',
      parentId: 'DocLayout',
    },
    'docs/demos/panelRender': {
      path: 'demos/panel-render',
      id: 'docs/demos/panelRender',
      parentId: 'DocLayout',
    },
    'docs/demos/switchType': {
      path: 'demos/switch-type',
      id: 'docs/demos/switchType',
      parentId: 'DocLayout',
    },
    'docs/demos/customize': {
      path: 'demos/customize',
      id: 'docs/demos/customize',
      parentId: 'DocLayout',
    },
    'docs/demos/calendar': {
      path: 'demos/calendar',
      id: 'docs/demos/calendar',
      parentId: 'DocLayout',
    },
    'docs/demos/basic': { path: 'demos/basic', id: 'docs/demos/basic', parentId: 'DocLayout' },
    'docs/demos/modes': { path: 'demos/modes', id: 'docs/demos/modes', parentId: 'DocLayout' },
    'docs/demos/panel': { path: 'demos/panel', id: 'docs/demos/panel', parentId: 'DocLayout' },
    'docs/demos/range': { path: 'demos/range', id: 'docs/demos/range', parentId: 'DocLayout' },
    'docs/demos/time': { path: 'demos/time', id: 'docs/demos/time', parentId: 'DocLayout' },
    'docs/demos/rtl': { path: 'demos/rtl', id: 'docs/demos/rtl', parentId: 'DocLayout' },
    'docs/index': { path: '', id: 'docs/index', parentId: 'DocLayout' },
    'demo-render': {
      id: 'demo-render',
      path: '~demos/:id',
      parentId: 'dumi-context-layout',
      prerender: false,
    },
  } as const;
  return {
    routes,
    routeComponents: {
      '404': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__dist__client__pages__404" */ '/Users/xx/Workspace/picker/node_modules/dumi/dist/client/pages/404.js'
          ),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */ '/Users/xx/Workspace/picker/.dumi/tmp/dumi/theme/ContextWrapper.tsx'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */ '/Users/xx/Workspace/picker/node_modules/dumi/theme-default/layouts/DocLayout/index.js'
          ),
      ),
      'docs/demos/disabledDate': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__demos__disabledDate.md" */ '/Users/xx/Workspace/picker/docs/demos/disabledDate.md'
          ),
      ),
      'docs/demos/uncontrolled': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__demos__uncontrolled.md" */ '/Users/xx/Workspace/picker/docs/demos/uncontrolled.md'
          ),
      ),
      'docs/demos/panelRender': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__demos__panelRender.md" */ '/Users/xx/Workspace/picker/docs/demos/panelRender.md'
          ),
      ),
      'docs/demos/switchType': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__demos__switchType.md" */ '/Users/xx/Workspace/picker/docs/demos/switchType.md'
          ),
      ),
      'docs/demos/customize': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__demos__customize.md" */ '/Users/xx/Workspace/picker/docs/demos/customize.md'
          ),
      ),
      'docs/demos/calendar': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__demos__calendar.md" */ '/Users/xx/Workspace/picker/docs/demos/calendar.md'
          ),
      ),
      'docs/demos/basic': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__demos__basic.md" */ '/Users/xx/Workspace/picker/docs/demos/basic.md'
          ),
      ),
      'docs/demos/modes': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__demos__modes.md" */ '/Users/xx/Workspace/picker/docs/demos/modes.md'
          ),
      ),
      'docs/demos/panel': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__demos__panel.md" */ '/Users/xx/Workspace/picker/docs/demos/panel.md'
          ),
      ),
      'docs/demos/range': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__demos__range.md" */ '/Users/xx/Workspace/picker/docs/demos/range.md'
          ),
      ),
      'docs/demos/time': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__demos__time.md" */ '/Users/xx/Workspace/picker/docs/demos/time.md'
          ),
      ),
      'docs/demos/rtl': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__demos__rtl.md" */ '/Users/xx/Workspace/picker/docs/demos/rtl.md'
          ),
      ),
      'docs/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.md" */ '/Users/xx/Workspace/picker/docs/index.md'
          ),
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */ '/Users/xx/Workspace/picker/node_modules/dumi/dist/client/pages/Demo/index.js'
          ),
      ),
    },
  };
}
