// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/demo/disabledDate":{"path":"demo/disabled-date","id":"docs/demo/disabledDate","parentId":"DocLayout"},"docs/demo/uncontrolled":{"path":"demo/uncontrolled","id":"docs/demo/uncontrolled","parentId":"DocLayout"},"docs/demo/panelRender":{"path":"demo/panel-render","id":"docs/demo/panelRender","parentId":"DocLayout"},"docs/demo/cellRender":{"path":"demo/cell-render","id":"docs/demo/cellRender","parentId":"DocLayout"},"docs/demo/switchType":{"path":"demo/switch-type","id":"docs/demo/switchType","parentId":"DocLayout"},"docs/demo/customize":{"path":"demo/customize","id":"docs/demo/customize","parentId":"DocLayout"},"docs/demo/calendar":{"path":"demo/calendar","id":"docs/demo/calendar","parentId":"DocLayout"},"docs/demo/locale":{"path":"demo/locale","id":"docs/demo/locale","parentId":"DocLayout"},"docs/demo/basic":{"path":"demo/basic","id":"docs/demo/basic","parentId":"DocLayout"},"docs/demo/modes":{"path":"demo/modes","id":"docs/demo/modes","parentId":"DocLayout"},"docs/demo/panel":{"path":"demo/panel","id":"docs/demo/panel","parentId":"DocLayout"},"docs/demo/range":{"path":"demo/range","id":"docs/demo/range","parentId":"DocLayout"},"docs/changelog":{"path":"changelog","id":"docs/changelog","parentId":"DocLayout"},"docs/demo/time":{"path":"demo/time","id":"docs/demo/time","parentId":"DocLayout"},"docs/demo/rtl":{"path":"demo/rtl","id":"docs/demo/rtl","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "dumi__pages__404" */'@/dumi__pages/404')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__ContextWrapper" */'@/dumi__theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__DocLayout" */'@/dumi__theme/layouts/DocLayout')),
'docs/demo/disabledDate': React.lazy(() => import(/* webpackChunkName: "docs__demo__disabledDate.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/disabledDate.md')),
'docs/demo/uncontrolled': React.lazy(() => import(/* webpackChunkName: "docs__demo__uncontrolled.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/uncontrolled.md')),
'docs/demo/panelRender': React.lazy(() => import(/* webpackChunkName: "docs__demo__panelRender.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/panelRender.md')),
'docs/demo/cellRender': React.lazy(() => import(/* webpackChunkName: "docs__demo__cellRender.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/cellRender.md')),
'docs/demo/switchType': React.lazy(() => import(/* webpackChunkName: "docs__demo__switchType.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/switchType.md')),
'docs/demo/customize': React.lazy(() => import(/* webpackChunkName: "docs__demo__customize.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/customize.md')),
'docs/demo/calendar': React.lazy(() => import(/* webpackChunkName: "docs__demo__calendar.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/calendar.md')),
'docs/demo/locale': React.lazy(() => import(/* webpackChunkName: "docs__demo__locale.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/locale.md')),
'docs/demo/basic': React.lazy(() => import(/* webpackChunkName: "docs__demo__basic.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/basic.md')),
'docs/demo/modes': React.lazy(() => import(/* webpackChunkName: "docs__demo__modes.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/modes.md')),
'docs/demo/panel': React.lazy(() => import(/* webpackChunkName: "docs__demo__panel.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/panel.md')),
'docs/demo/range': React.lazy(() => import(/* webpackChunkName: "docs__demo__range.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/range.md')),
'docs/changelog': React.lazy(() => import(/* webpackChunkName: "docs__changelog.md" */'/Users/jilin/projects/antd/rc-picker/docs/changelog.md')),
'docs/demo/time': React.lazy(() => import(/* webpackChunkName: "docs__demo__time.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/time.md')),
'docs/demo/rtl': React.lazy(() => import(/* webpackChunkName: "docs__demo__rtl.md" */'/Users/jilin/projects/antd/rc-picker/docs/demo/rtl.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/jilin/projects/antd/rc-picker/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "dumi__pages__Demo" */'@/dumi__pages/Demo')),
},
  };
}
