// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/jilin/projects/antd/rc-picker/node_modules/_dumi@2.2.6@dumi/theme-default/slots/Header/index.js';
