// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '/Users/xx/Workspace/picker/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export { default } from '/Users/xx/Workspace/picker/node_modules/dumi/theme-default/slots/SearchBar/index.js';
