// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import {
  demos as dm6,
  frontmatter as fm6,
  texts as txt6,
  toc as toc6,
} from '/Users/xx/Workspace/picker/docs/demos/basic.md?type=meta';
import {
  demos as dm5,
  frontmatter as fm5,
  texts as txt5,
  toc as toc5,
} from '/Users/xx/Workspace/picker/docs/demos/calendar.md?type=meta';
import {
  demos as dm4,
  frontmatter as fm4,
  texts as txt4,
  toc as toc4,
} from '/Users/xx/Workspace/picker/docs/demos/customize.md?type=meta';
import {
  demos as dm0,
  frontmatter as fm0,
  texts as txt0,
  toc as toc0,
} from '/Users/xx/Workspace/picker/docs/demos/disabledDate.md?type=meta';
import {
  demos as dm7,
  frontmatter as fm7,
  texts as txt7,
  toc as toc7,
} from '/Users/xx/Workspace/picker/docs/demos/modes.md?type=meta';
import {
  demos as dm8,
  frontmatter as fm8,
  texts as txt8,
  toc as toc8,
} from '/Users/xx/Workspace/picker/docs/demos/panel.md?type=meta';
import {
  demos as dm2,
  frontmatter as fm2,
  texts as txt2,
  toc as toc2,
} from '/Users/xx/Workspace/picker/docs/demos/panelRender.md?type=meta';
import {
  demos as dm9,
  frontmatter as fm9,
  texts as txt9,
  toc as toc9,
} from '/Users/xx/Workspace/picker/docs/demos/range.md?type=meta';
import {
  demos as dm11,
  frontmatter as fm11,
  texts as txt11,
  toc as toc11,
} from '/Users/xx/Workspace/picker/docs/demos/rtl.md?type=meta';
import {
  demos as dm3,
  frontmatter as fm3,
  texts as txt3,
  toc as toc3,
} from '/Users/xx/Workspace/picker/docs/demos/switchType.md?type=meta';
import {
  demos as dm10,
  frontmatter as fm10,
  texts as txt10,
  toc as toc10,
} from '/Users/xx/Workspace/picker/docs/demos/time.md?type=meta';
import {
  demos as dm1,
  frontmatter as fm1,
  texts as txt1,
  toc as toc1,
} from '/Users/xx/Workspace/picker/docs/demos/uncontrolled.md?type=meta';
import {
  demos as dm12,
  frontmatter as fm12,
  texts as txt12,
  toc as toc12,
} from '/Users/xx/Workspace/picker/docs/index.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/demos/disabledDate': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/demos/uncontrolled': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/demos/panelRender': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/demos/switchType': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/demos/customize': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/demos/calendar': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/demos/basic': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/demos/modes': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/demos/panel': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'docs/demos/range': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'docs/demos/time': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'docs/demos/rtl': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'docs/index': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
};

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
