// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { history, useOutlet } from 'dumi';
import React, { useEffect, useRef, useState } from 'react';
import { locales } from '../locales/config';
import { components, demos } from '../meta';
import { SiteContext } from '/Users/xx/Workspace/picker/node_modules/dumi/dist/client/theme-api/context.js';

const entryExports = {};

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(true);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // mark loading when route change, page component will set false when loaded
        setLoading(true);

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider
      value={{
        pkg: {
          name: 'rc-picker',
          description: 'React date & time picker',
          version: '3.1.5',
          license: 'MIT',
          repository: { type: 'git', url: 'git@github.com:react-component/picker.git' },
        },
        entryExports,
        demos,
        components,
        locales,
        loading,
        setLoading,
        themeConfig: {
          footer:
            'Copyright © 2023 | Powered by <a href="https://d.umijs.org" target="_blank" rel="noreferrer">dumi</a>',
          prefersColor: { default: 'light', switch: true },
          name: 'rc-picker',
          logo: 'https://avatars0.githubusercontent.com/u/9441414?s=200&v=4',
        },
      }}
    >
      {outlet}
    </SiteContext.Provider>
  );
}
